### PR TITLE
Replaced switch statement with Day enum

### PR DESCRIPTION
**Pull request by YourSenseiCreeper**
Hi!

### CODE REVIEW

**Comment by YourSenseiCreeper** [comment]
Uhm.. yes, you're right. But I hope we still can improve it anyway. Found this (if the sequence of numbers when you add days doesn't matter):
`Map<Integer,String> map = Map.of(1, "monday", 2, "tuesday", 3, "wednesday", 4, "thursday", 5, "friday", 6, "saturday", 7, "sunday");` 
` //External method int getDayNumber(String day)` 
` int index = 0;` 
`     for(Map.Entry<Integer, String> entry : map.entrySet()){` 
`       if(entry.getValue() == "tuesday") index = entry.getKey();` 
`     }` 
`return index;`
`//End of external method`
` String occasionDay = singleOccasion.toLowerCase();` 
` if (map.containsValue(singleOccasion.toLowerCase()){` 
`     timer.addDay(getDayNumber(occasionDay));` 
`}` 
And for adding whole week you can simply use
`for(int day : map.keySet()){` 
`     timer.addDay(day);` 
` }`
Or use lambda expression 
`map.keySet().forEach(day -> timer.addDay(day));`

**Comment by NiklasEi** [comment]
You can leave the enum, no reason for the map. If an entry is successfully parsed as day, add the day, otherwise try pasing to int and saving as month date.

**Comment by YourSenseiCreeper** [comment]
It's up to you. To me map is more convenient way - you can add whole week at once. Moreover parsing is not based on try catch statement, but on containsKey. Anyway I must admit I've never discussed so much about a little chunk of code. I did change because I like the idea of the plugin - it's simple, but original and very useful. Do you mind if I look through the code and try to improve it a bit more?

**Comment by NiklasEi** [comment]
Sure, go ahead.

**Pull request closed without merging**
